---
AWSTemplateFormatVersion: "2010-09-09"

Description:
  This is the first cloudformation template to create s3 bucket 

Resources:
 MarcusS3bucket: 
  Type: AWS::S3::Bucket
  Properties:
    BucketName: demobucket4963
    



